export const items = [
  {
    id: 1,
    title: "Italy",
    price: "500",
    description: "A beautiful place in Asia.",
    imageUrl: "/Images/ID.webp",
    link: "/italy",
  },
  {
    id: 2,
    title: "Bhutan",
    price: "800",
    description: "Known for its diversity.",
    imageUrl: "/Images/SG.webp",
    link: "/bhutan",
  },
  {
    id: 3,
    title: "UAE",
    price: "700",
    description: "Famous for its art and history.",
    imageUrl: "/Images/EG.webp",
    link: "/uae",
  },
  {
    id: 4,
    title: "Italy",
    price: "600",
    description: "Home to beautiful landscapes.",
    imageUrl: "/Images/MY.webp",
  },
  {
    id: 5,
    title: "Germany",
    price: "650",
    description: "Known for its rich culture.",
    imageUrl: "/Images/ID.webp",
  },
  {
    id: 6,
    title: "Canada",
    price: "750",
    description: "A country with stunning nature.",
    imageUrl: "/Images/SG.webp",
  },
  {
    id: 7,
    title: "Japan",
    price: "900",
    description: "Land of the rising sun.",
    imageUrl: "/Images/EG.webp",
  },
  {
    id: 8,
    title: "Australia",
    price: "850",
    description: "A land full of adventures.",
    imageUrl: "/Images/MY.webp",
  },
  {
    id: 9,
    title: "Brazil",
    price: "400",
    description: "Famous for its vibrant culture.",
    imageUrl: "/Images/EG.webp",
  },
];
